package jezorko.github.gfngameslist.games

val keywords = listOf(
    "2d",
    "3d",
    "3rd person",
    "4 player local",
    "4x",
    "abstract",
    "acii",
    "action",
    "action adventure",
    "action rpg",
    "addictive",
    "adorable",
    "adventure",
    "agriculture",
    "airforce",
    "aliens",
    "alternate history",
    "ambiance",
    "animal",
    "anime",
    "arcade",
    "army",
    "artificial intelligence",
    "assassin",
    "atmospheric",
    "automation",
    "automobile sim",
    "base building",
    "baseball",
    "based on a novel",
    "battle",
    "battle royale",
    "benchmark",
    "blood",
    "bmx",
    "boats",
    "bombs",
    "book",
    "builder",
    "building",
    "bulldoze",
    "bullet hell",
    "bullet time",
    "bus",
    "card",
    "cards",
    "cars",
    "cartoon",
    "casual",
    "cat",
    "cats",
    "character customization",
    "chat",
    "choices",
    "choices matter",
    "city",
    "class based",
    "classic",
    "clicker",
    "co op",
    "co op campaign",
    "co op online",
    "cold war",
    "colony",
    "colorful",
    "combat",
    "comedy",
    "comic",
    "competitive",
    "conspiracy",
    "construction",
    "controller",
    "coop online",
    "court",
    "cozy",
    "craft",
    "crafting",
    "crane",
    "crawler",
    "creative",
    "creature",
    "crime",
    "cross platform",
    "crowdfunded",
    "crowdfunding",
    "cuisine",
    "cult",
    "curse",
    "cute",
    "cyber",
    "cyberpunk",
    "cycling",
    "dark",
    "dark fantasy",
    "dark humor",
    "dating",
    "dead",
    "decks",
    "defense",
    "demo",
    "demons",
    "desert",
    "destruction",
    "detective",
    "difficult",
    "dig",
    "dinosaurs",
    "dive",
    "dlss",
    "dog fight",
    "dogs",
    "dragons",
    "drama",
    "dream",
    "driver",
    "driving",
    "drone",
    "drug",
    "dungeon",
    "dungeon crawler",
    "dungeons",
    "dwarf",
    "dynamic narration",
    "dystopia",
    "dystopian",
    "e sport",
    "e sports",
    "early access",
    "economy",
    "education",
    "elves",
    "emotional",
    "empire",
    "epic",
    "esports",
    "experience",
    "experimental",
    "exploration",
    "explosions",
    "extinction",
    "faith",
    "fantasy",
    "farm",
    "farming",
    "fast",
    "fast paced",
    "fate",
    "female protagonist",
    "fiction",
    "fight",
    "fighter",
    "fighting",
    "film",
    "first person",
    "first person adventure",
    "first person shooter",
    "fish",
    "fishing",
    "flight",
    "fluid",
    "flying",
    "football",
    "foreign",
    "forest",
    "forge",
    "forts",
    "fpp",
    "fps",
    "free",
    "free to play",
    "fun",
    "funny",
    "future",
    "futuristic",
    "gambling",
    "ghost",
    "god",
    "golf",
    "gore",
    "gothic",
    "great soundtrack",
    "grind",
    "hack",
    "hack & slash",
    "hack 'n' slash",
    "hack and slash",
    "hacking",
    "halloween",
    "hand drawn",
    "hardware",
    "heist",
    "hero",
    "heroes",
    "hidden",
    "hide",
    "highlights",
    "historical",
    "horror",
    "horses",
    "hospital",
    "humor",
    "humour",
    "hunt",
    "hunting",
    "illuminati",
    "immersive",
    "immortal",
    "indie",
    "infiltration",
    "intense",
    "interactive",
    "inventory management",
    "investigation",
    "isometric",
    "jet",
    "kids",
    "killing",
    "kittens",
    "knight",
    "kung fu",
    "lemmings",
    "level editor",
    "lgbtq+",
    "life",
    "linear",
    "lineart",
    "local co op",
    "local multiplayer",
    "loot",
    "looter shooter",
    "lovecraft",
    "lovecraftian",
    "lunar",
    "magic",
    "management",
    "manipulation",
    "massively multiplayer",
    "masterpiece",
    "mature",
    "meat",
    "mech",
    "medical",
    "medieval",
    "memes",
    "merchant",
    "metamorphosis",
    "metroidvania",
    "militar",
    "military",
    "minimalist",
    "mining",
    "minion",
    "mma",
    "mmo",
    "mmorpg",
    "moba",
    "moddable",
    "modding",
    "modern",
    "monkeys",
    "monster",
    "moon",
    "motorbike",
    "motorcycle",
    "multiplayer",
    "multiple endings",
    "music",
    "mutant",
    "mutliplayer",
    "mystery",
    "mythology",
    "nature",
    "naval",
    "naval combat",
    "ninja",
    "noir",
    "nsfw",
    "nudity",
    "nvidia",
    "nvidia highlights",
    "observation",
    "ocean",
    "off road",
    "offroad",
    "old school",
    "olympics",
    "online",
    "online co op",
    "open world",
    "parkour",
    "parkur",
    "party",
    "perma death",
    "permadeath",
    "pets",
    "philosophical",
    "physics",
    "pirates",
    "pixel graphics",
    "pixels",
    "plague",
    "plane",
    "planes",
    "platformer",
    "political",
    "pool",
    "post apocalyptic",
    "prison",
    "procedural",
    "programming",
    "psychological",
    "punk",
    "puzzle",
    "pve",
    "pvp",
    "quad",
    "quest",
    "quick time events",
    "race",
    "racing",
    "rail",
    "ray tracing",
    "real time",
    "real time tactics",
    "real time with pause",
    "realistic",
    "reboot",
    "relaxing",
    "religion",
    "remake",
    "remaster",
    "replay value",
    "retro",
    "revolution",
    "rhythm",
    "road",
    "robots",
    "roguelike",
    "roguelite",
    "romance",
    "rpg",
    "rts",
    "rtx",
    "runner",
    "rural",
    "sailing",
    "samurai",
    "sand",
    "sandbox",
    "satire",
    "sci fi",
    "science fiction",
    "scifi",
    "scroller",
    "secret",
    "sentimental",
    "sequel",
    "sexual content",
    "shark",
    "shooter",
    "short",
    "silent protagonist",
    "sim",
    "simulation",
    "singleplayer",
    "skate",
    "ski",
    "sniper",
    "snooker",
    "snow",
    "snowboard",
    "soccer",
    "social",
    "soldier",
    "solo",
    "soul",
    "space",
    "space sim",
    "spaceship",
    "spectacle",
    "spells",
    "split screen",
    "splitscreen",
    "sport",
    "sports",
    "stealth",
    "steam punk",
    "steampunk",
    "story rich",
    "strategy",
    "stylized",
    "superhero",
    "supernatural",
    "surreal",
    "survival",
    "survival horror",
    "suspense",
    "sweaters",
    "sword",
    "swordplay",
    "tactical",
    "tanks",
    "team based",
    "teamplay",
    "teamwork",
    "tenis",
    "terror",
    "text",
    "text based",
    "thief",
    "third person",
    "third person shooter",
    "thriller",
    "time",
    "time manipulation",
    "tool",
    "top down",
    "top down shooter",
    "tower defense",
    "towers",
    "town",
    "tps",
    "trading",
    "trains",
    "transhumanism",
    "transport",
    "trophy",
    "turn",
    "turn based",
    "turn based strategy",
    "tutorial",
    "twin stick shooter",
    "tycoon",
    "typing",
    "tyranny",
    "unforgiving",
    "universe",
    "vampire",
    "viking",
    "villain",
    "violence",
    "violent",
    "visual novel",
    "voice control",
    "voxel",
    "walking",
    "war",
    "water",
    "western",
    "wings",
    "witch",
    "wolves",
    "world war",
    "wrestling",
    "wwii",
    "zombie",
    "zombies",
    "zoo"
)